site_name: Assistente SEI para Microsoft Teams
site_description: Documentação completa do projeto de integração SEI com Microsoft Teams
site_author: Marcos Marinho

theme:
  name: material
  language: pt-BR
  palette:
    - scheme: default
      primary: gray
      accent: lime
      toggle:
        icon: material/weather-night
        name: Alternar para modo escuro
    - scheme: slate
      primary: deep gray
      accent: lime
      toggle:
        icon: material/weather-sunny
        name: Alternar para modo claro
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.expand
    - navigation.top
    - navigation.tabs
    - navigation.instant
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
    - content.action.edit
    - content.tabs.link
    - content.tooltips
    - toc.integrate
nav:
  - Início: index.md
  - Funcionalidades: funcionalidades.md
  - Status e Próximos Passos: status-e-proximos-passos.md
  - Arquitetura Técnica: arquitetura-tecnica.md
  - Guia de Implementação: guia-implementacao.md

markdown_extensions:
  - toc:
      permalink: true
  - footnotes
  - def_list
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - attr_list
  - codehilite
  - abbr


extra_css:
  - stylesheets/custom.css  # se quiser personalizar com seu estilo

extra_javascript:
  - javascripts/custom.js  # opcional para JS extra

plugins:
  - search
  - mkdocstrings